### ISSUE TITLE
MIPS async segfault

### ISSUE THREAD

**Issue by waulkrie** [jgaa/RESTinCurl#1]
Really enjoying this nice library you have here, top notch. Honestly, I love it. I just had this one bug I couldn't figure out for awhile. If curl returns an error code of 6 while RESTinCurl is in async mode I encounter a segfault (writing to address nulltpr) right after the EasyHandle deconstructor is called it appears. Mind you this is only in mipsel_24k architecture as far as I've found. Going back to synchronous mode solved the problem for me. If you are further interested I'll try to be of any help you need.

**Comment by jgaa** [comment]
Is there anyway I can reproduce this? Are you using real hardware or an emulator?

**Comment by jgaa** [comment]
No feedback. No way to reproduce.
