### ISSUE TITLE
Does RESTinCurl supports file upload with POST request

### ISSUE THREAD

**Issue by Akki-401** [jgaa/RESTinCurl#3]
Hii @jgaa,

Does this library supports file upload with POST request?
In my project, using a this library and i'm not able to find a way how to upload a file with this lib.

**Comment by jgaa** [comment]
No. It has not been a use-case until now, so I haven't thought about it.

An extra method to send a file should be relatively simple to add, so I guess I will do that.

**Comment by Akki-401** [comment]
Thanks @jgaa for the prompt response especially during this vacation time.

It would be very useful for my case, if it can be done quickly.
Could you please tell me ETA of it.

**Comment by jgaa** [comment]
I have made a simple implementation in a new branch [upload-file)(https://github.com/jgaa/RESTinCurl/tree/upload-file). I need to write some more tests and validate it a little more thoroughly, so it will be a few days until it's in the maser branch.  Feel free to play with it and please report any problems.

**Comment by Akki-401** [comment]
Definitely, will make use of it and let you know if i come across any issue. 
Thanks a lot!

**Comment by Akki-401** [comment]
@jgaa Please consider "multipart/form-data; **boundary=<value>**" as Content-Type in POST request while adding support of it.
I'm not seeing boundary is getting added when Content-Type is multipart/form-data

**Comment by jgaa** [comment]
I added a second method to send files, this time as MIME attachments, which is probably what you need. You can see the example in `upload_test.cpp`.

**Comment by jgaa** [comment]
Implementation merged to master
